# Generated by Django 5.2.11 on 2026-02-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
