# Generated by Django 5.2.11 on 2026-02-05 18:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_request_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': '??????', 'verbose_name_plural': '??????'},
        ),
        migrations.AlterModelOptions(
            name='verificationresult',
            options={'verbose_name': '????????? ????????', 'verbose_name_plural': '?????????? ????????'},
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='??????????'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('CREATED', '???????'), ('VERIFIED', '??????????????'), ('IN_PROGRESS', '? ??????'), ('ON_CHECK', '?? ????????'), ('COMPLETED', '?????????')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=255, verbose_name='????????'),
        ),
        migrations.CreateModel(
            name='RequestRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rework_events', to=settings.AUTH_USER_MODEL)),
                ('new_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_events_new_worker', to=settings.AUTH_USER_MODEL)),
                ('previous_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_events_previous_worker', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_events', to='requests_app.request')),
            ],
            options={
                'verbose_name': '??????? ?? ?????????',
                'verbose_name_plural': '???????? ?? ?????????',
                'ordering': ('-created_at',),
            },
        ),
    ]
