# Generated by Django 5.2.11 on 2026-03-18 13:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_alter_request_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Субъект РФ',
                'verbose_name_plural': 'Субъекты РФ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('CITY', 'Город'), ('TOWN', 'Посёлок городского типа'), ('SETTLEMENT', 'Посёлок'), ('VILLAGE', 'Село'), ('HAMLET', 'Деревня'), ('OTHER', 'Иное')], default='CITY', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OwnershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип собственности',
                'verbose_name_plural': 'Типы собственности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TerritoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_external_transfer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип территории',
                'verbose_name_plural': 'Типы территорий',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='requestrework',
            options={'ordering': ('-created_at',), 'verbose_name': 'Возврат на доработку', 'verbose_name_plural': 'Возвраты на доработку'},
        ),
        migrations.AlterModelOptions(
            name='verificationresult',
            options={'verbose_name': 'Результат проверки', 'verbose_name_plural': 'Результаты проверки'},
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='classification_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='handling_mode',
            field=models.CharField(choices=[('CLEANUP', 'Уборка'), ('EXTERNAL_TRANSFER', 'Внешняя передача')], default='CLEANUP', max_length=32),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Геопозиция'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('VERIFIED', 'Верифицирована'), ('IN_PROGRESS', 'В работе'), ('ON_CHECK', 'На проверке'), ('COMPLETED', 'Завершена'), ('TRANSFERRED', 'Передана по принадлежности')], db_index=True, default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('brigade_type', models.CharField(choices=[('CLEANUP', 'Уборочная бригада'), ('CONTRACTOR', 'Подрядная бригада'), ('MOBILE', 'Мобильная группа'), ('OTHER', 'Иное')], default='CLEANUP', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='brigades', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_brigades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='request',
            name='assigned_brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.brigade'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('department_type', models.CharField(choices=[('DISPATCH', 'Диспетчеризация'), ('TERRITORIAL', 'Территориальный участок'), ('CLEANUP', 'Уборка'), ('ADMINISTRATION', 'Администрирование'), ('OTHER', 'Иное')], default='OTHER', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='requests_app.department')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='brigade',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigades', to='requests_app.department'),
        ),
        migrations.AddField(
            model_name='request',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.department'),
        ),
        migrations.AddField(
            model_name='request',
            name='federal_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.federalsubject'),
        ),
        migrations.AddField(
            model_name='request',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.locality'),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('MUNICIPAL_DISTRICT', 'Муниципальный район'), ('CITY_DISTRICT', 'Городской округ'), ('URBAN_SETTLEMENT', 'Городское поселение'), ('RURAL_SETTLEMENT', 'Сельское поселение'), ('INTRACITY_DISTRICT', 'Внутригородской район'), ('OTHER', 'Иное')], default='CITY_DISTRICT', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('federal_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='requests_app.federalsubject')),
            ],
            options={
                'verbose_name': 'Муниципальное образование',
                'verbose_name_plural': 'Муниципальные образования',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='requests_app.municipality'),
        ),
        migrations.AddField(
            model_name='request',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.municipality'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('federal_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='requests_app.federalsubject')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='requests_app.locality')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='requests_app.municipality')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='requests_app.organizationtype')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_contact', models.CharField(blank=True, default='', max_length=255)),
                ('transfer_reason', models.TextField()),
                ('comment', models.TextField(blank=True, default='')),
                ('outgoing_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('ACCEPTED', 'Принято'), ('CLOSED', 'Закрыто')], default='SENT', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_transfers', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transfers', to='requests_app.request')),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_transfers', to='requests_app.organization')),
            ],
            options={
                'verbose_name': 'Внешняя передача',
                'verbose_name_plural': 'Внешние передачи',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='requests_app.organization'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigades', to='requests_app.organization'),
        ),
        migrations.AddField(
            model_name='request',
            name='responsible_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_requests', to='requests_app.organization'),
        ),
        migrations.AddField(
            model_name='request',
            name='ownership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.ownershiptype'),
        ),
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('ROUTING', 'Маршрутизация'), ('WORKER', 'Назначение исполнителя'), ('REASSIGNMENT', 'Переназначение'), ('EXTERNAL_TRANSFER', 'Внешняя передача')], default='ROUTING', max_length=24)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='requests_app.brigade')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_request_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='requests_app.department')),
                ('assigned_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='requests_app.organization')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='requests_app.request')),
            ],
            options={
                'verbose_name': 'Назначение заявки',
                'verbose_name_plural': 'Назначения заявок',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('VERIFIED', 'Верифицирована'), ('IN_PROGRESS', 'В работе'), ('ON_CHECK', 'На проверке'), ('COMPLETED', 'Завершена'), ('TRANSFERRED', 'Передана по принадлежности')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.request')),
            ],
            options={
                'verbose_name': 'История статусов заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_zones', to='requests_app.brigade')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_zones', to='requests_app.department')),
                ('federal_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_zones', to='requests_app.federalsubject')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_zones', to='requests_app.locality')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_zones', to='requests_app.municipality')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_zones', to='requests_app.organization')),
                ('territory_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_zones', to='requests_app.territorytype')),
            ],
            options={
                'verbose_name': 'Зона ответственности',
                'verbose_name_plural': 'Зоны ответственности',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='request',
            name='territory_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.territorytype'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', 'created_at'], name='request_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['handling_mode', 'created_at'], name='request_handling_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('federal_subject', 'name', 'kind'), name='uniq_municipality_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('municipality', 'name', 'kind'), name='uniq_locality_per_municipality'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_department_per_org'),
        ),
        migrations.AddConstraint(
            model_name='brigade',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_brigade_per_org'),
        ),
    ]
