# Generated by Django 5.2.12 on 2026-05-12 22:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_seed_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], db_index=True, default='DRAFT', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL)),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='requests_app.brigade')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='requests_app.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='requests_app.organization')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_points', to='requests_app.request')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='requests_app.route')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ('order_number', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status', 'created_at'], name='route_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['organization', 'status'], name='route_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='routepoint',
            constraint=models.UniqueConstraint(fields=('route', 'request'), name='uniq_route_point_request'),
        ),
        migrations.AddConstraint(
            model_name='routepoint',
            constraint=models.UniqueConstraint(fields=('route', 'order_number'), name='uniq_route_point_order'),
        ),
    ]
