# Generated by Django 5.2.12 on 2026-05-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0007_route_routepoint_route_route_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
