services:
  db:
    image: postgis/postgis:16-3.4
    container_name: garbage_postgis
    environment:
      POSTGRES_DB: garbage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: garbage_django
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_NAME: garbage_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      DEFAULT_FROM_EMAIL: emilka22866@mail.ru
      EMAIL_HOST: smtp.mail.ru
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: emilka22866@mail.ru
      EMAIL_HOST_PASSWORD: N9PixYSevoNYL0BndnrZ
      EMAIL_USE_TLS: "True"
      FRONTEND_BASE_URL: "http://localhost:3000"
      YANDEX_GEOCODER_API_KEY: "78f20bd4-10d4-4100-9d65-5114f1733cfd"
      AI_CONF_THRESHOLD: "0.5"
      AI_MIN_REDUCTION: "0.8"
      AI_MAX_AFTER: "0"

  frontend:
    image: node:20-alpine
    container_name: garbage_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"

volumes:
  pgdata:
