# Generated by Django 5.2.12 on 2026-03-30 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_seed_reference_data'),
        ('users', '0004_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='requests_app.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='requests_app.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Гражданин'), ('WORKER', 'Исполнитель'), ('COORDINATOR', 'Координатор'), ('ORG_MANAGER', 'Руководитель организации'), ('ADMIN', 'Администратор')], default='CITIZEN', max_length=20),
        ),
    ]
