# Generated by Codex on 2026-03-30

from django.db import migrations, models


def populate_user_affiliations(apps, schema_editor):
    User = apps.get_model("users", "User")
    Brigade = apps.get_model("requests_app", "Brigade")
    Request = apps.get_model("requests_app", "Request")

    for user in User.objects.filter(organization__isnull=True).exclude(role="CITIZEN").exclude(role="ADMIN"):
        brigade = (
            Brigade.objects.filter(models.Q(supervisor_id=user.id) | models.Q(members=user))
            .order_by("id")
            .first()
        )
        if brigade:
            user.organization_id = brigade.organization_id
            user.department_id = brigade.department_id
            user.save(update_fields=["organization", "department"])
            continue

        request = (
            Request.objects.filter(assigned_worker_id=user.id, responsible_organization__isnull=False)
            .order_by("-updated_at", "-id")
            .first()
        )
        if request:
            user.organization_id = request.responsible_organization_id
            user.department_id = request.responsible_department_id
            user.save(update_fields=["organization", "department"])

    for user in User.objects.filter(organization__isnull=True, department__isnull=False):
        department = user.department
        if department:
            user.organization_id = department.organization_id
            user.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_department_user_organization_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(populate_user_affiliations, migrations.RunPython.noop),
    ]
