# Generated by Codex on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_populate_user_affiliations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Гражданин"),
                    ("WORKER", "Исполнитель"),
                    ("COORDINATOR", "Координатор"),
                    ("ORG_MANAGER", "Руководитель организации"),
                    ("DEPARTMENT_MANAGER", "Руководитель подразделения"),
                    ("ADMIN", "Администратор"),
                ],
                default="CITIZEN",
                max_length=20,
            ),
        ),
    ]
